### ISSUE TITLE
niclist.exe crashes

### ISSUE THREAD

**Issue by sskras** [bochs-emu/Bochs#161]
`niclist.exe` binary just crashes on my w10 without any output.
So I launched it in a debugger. Here you see it catches the `EXCEPTION_ACCESS_VIOLATION`:
```
$ /d/Downloads/radare2-5.8.8-w64/bin/radare2 -d niclist.exe
INFO: Spawned new process with pid 2164, tid = 10272
[0x7ffd62d826d0]> dc
(2164) loading library at 0x00007FFD62D30000 (C:\Windows\System32\ntdll.dll) ntdll.dll
(2164) loading library at 0x00007FFD62970000 (C:\Windows\System32\kernel32.dll) kernel32.dll
(2164) loading library at 0x00007FFD60660000 (C:\Windows\System32\KernelBase.dll) KernelBase.dll
[0x7ffd62e00991]> dc
(2164) loading library at 0x00007FFD49320000 (C:\Windows\System32\Packet.dll) Packet.dll
(2164) Created thread 6820 (start @ 00007FFD62D82B70) (teb @ 0000008AAA8BF000)
(2164) loading library at 0x00007FFD62550000 (C:\Windows\System32\ws2_32.dll) ws2_32.dll
(2164) loading library at 0x00007FFD62720000 (C:\Windows\System32\rpcrt4.dll) rpcrt4.dll
(2164) Created thread 2964 (start @ 00007FFD62D82B70) (teb @ 0000008AAA8C1000)
(2164) loading library at 0x00007FFD62670000 (C:\Windows\System32\advapi32.dll) advapi32.dll
(2164) loading library at 0x00007FFD62C40000 (C:\Windows\System32\msvcrt.dll) msvcrt.dll
(2164) loading library at 0x00007FFD61B90000 (C:\Windows\System32\sechost.dll) sechost.dll
(2164) loading library at 0x00007FFD61CE0000 (C:\Windows\System32\shell32.dll) shell32.dll
(2164) loading library at 0x00007FFD60CC0000 (C:\Windows\System32\msvcp_win.dll) msvcp_win.dll
(2164) Created thread 10816 (start @ 00007FFD62D82B70) (teb @ 0000008AAA8C3000)
(2164) loading library at 0x00007FFD60960000 (C:\Windows\System32\ucrtbase.dll) ucrtbase.dll
(2164) loading library at 0x00007FFD5F7D0000 (C:\Windows\System32\IPHLPAPI.DLL) IPHLPAPI.DLL
(2164) loading library at 0x00007FFD60DC0000 (C:\Windows\System32\user32.dll) user32.dll
(2164) loading library at 0x00007FFD60530000 (C:\Windows\System32\win32u.dll) win32u.dll
(2164) loading library at 0x00007FFD44080000 (C:\Windows\System32\winmm.dll) winmm.dll
(2164) loading library at 0x00007FFD55A70000 (C:\Windows\System32\version.dll) version.dll
(2164) loading library at 0x00007FFD61CB0000 (C:\Windows\System32\gdi32.dll) gdi32.dll
(2164) loading library at 0x00007FFD60410000 (C:\Windows\System32\gdi32full.dll) gdi32full.dll
(2164) loading library at 0x00007FFD60D90000 (C:\Windows\System32\imm32.dll) imm32.dll
(2164) Fatal Exception C0000005 (EXCEPTION_ACCESS_VIOLATION) in thread 10272
Hint: Use 'dce' continue into exception handler
[0x7ff6d6748a6a]> dbt
0  0x7ff6d6748a6a     sp: 0x0                 0    [??]  rip entry0+29542
1  0x7ff6d67410b3     sp: 0x8aaaafef38        88   [??]  main+163
[0x7ff6d6748a6a]> pd-- 10
        :   0x7ff6d6748a4d      49ffc3         inc r11
        :   0x7ff6d6748a50      83e107         and ecx, 7
        :   0x7ff6d6748a53      49c1e803       shr r8, 3
        :   0x7ff6d6748a57      d3e2           shl edx, cl
        :   0x7ff6d6748a59      4284540420     test byte [rsp + r8 + 0x20], dl
       ,==< 0x7ff6d6748a5e      750a           jne 0x7ff6d6748a6a
       |:   0x7ff6d6748a60      4d8bcb         mov r9, r11
       |:   0x7ff6d6748a63      453813         cmp byte [r11], r10b
       |`=< 0x7ff6d6748a66      75d9           jne 0x7ff6d6748a41
       |,=< 0x7ff6d6748a68      eb06           jmp 0x7ff6d6748a70
            ;-- rip:
            0x7ff6d6748a6a      458811         mov byte [r9], r10b
            0x7ff6d6748a6d      4d8bcb         mov r9, r11
            0x7ff6d6748a70      4c3bdb         cmp r11, rbx
            0x7ff6d6748a73      4c890f         mov qword [rdi], r9
            0x7ff6d6748a76      4c0f45d3       cmovne r10, rbx
            0x7ff6d6748a7a      498bc2         mov rax, r10
            0x7ff6d6748a7d      488b4c2440     mov rcx, qword [rsp + 0x40]
            0x7ff6d6748a82      4833cc         xor rcx, rsp
            0x7ff6d6748a85      e8f689ffff     call 0x7ff6d6741480
            0x7ff6d6748a8a      488b5c2478     mov rbx, qword [rsp + 0x78]
```

**Comment by sskras** [comment]
I removed it and installed v1.78 using the Wireshark setup guide.
As I saw no instructions about installing it, I went with the default settings for Npcap:

![image](https://github.com/bochs-emu/Bochs/assets/7887758/19e39966-6022-4b1f-a290-852f1e6b114f)

Note the third option:

> - [ ] **Install Npcap in WinPcap API-compatible Mode**

And now `niclist` really started behave like @vruppert wrote:
```
$ "D:\Program Files\Bochs-2.7\niclist.exe"
Could not load WinPCap driver!
You can download them for free from
http://www.winpcap.org/

Press any key to continue
```

So I reinstalled it again while enabling the **WinPcap API-compatible Mode**:
```
$ winget list | grep -iw npcap
Npcap                                  NpcapInst                              1.78
```

And now it segfaults again:
```
$ "D:\Program Files\Bochs-2.7\niclist.exe"
Segmentation fault
```

**Comment by sskras** [comment]
OK, so I compiled it using MinGW GCC and included debug-info:
```
$ gcc -o niclist.exe -g niclist.c

$ ldd niclist.exe
        ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x7ff9be2f0000)
        KERNEL32.DLL => /c/Windows/System32/KERNEL32.DLL (0x7ff9bda40000)
        KERNELBASE.dll => /c/Windows/System32/KERNELBASE.dll (0x7ff9bbbb0000)
        msvcrt.dll => /c/Windows/System32/msvcrt.dll (0x7ff9bdc00000)

$ ll niclist.exe
-rwxr-xr-x 1 saukrs None 306605 Dec 17 15:30 niclist.exe
```

Running under Radare2 exhibits same output (no debug symbols seen). So I went with the **gdb**:
```
$ gdb -q niclist.exe
Reading symbols from niclist.exe...
(gdb)
(gdb) br main
Breakpoint 1 at 0x140001545: file D:/_BACKUPS/src/github.com/bochs-emu/Bochs/Bochs/bochs/misc/niclist.c, line 77.
(gdb) #
(gdb) r
Starting program: /D/_BACKUPS/src/github.com/bochs-emu/Bochs/Bochs/bochs/misc/niclist.exe
[New Thread 3972.0x39b8]

Thread 1 hit Breakpoint 1, main (argc=1, argv=0xb224b0) at D:/_BACKUPS/src/github.com/bochs-emu/Bochs/Bochs/bochs/misc/niclist.c:77
77          char          AdapterInfo[NIC_BUFFER_SIZE] = { '\0','\0' };
(gdb) bt
#0  main (argc=1, argv=0xb224b0) at D:/_BACKUPS/src/github.com/bochs-emu/Bochs/Bochs/bochs/misc/niclist.c:77
(gdb) #
(gdb) info th
  Id   Target Id          Frame
* 1    Thread 3972.0x174c main (argc=1, argv=0xb224b0) at D:/_BACKUPS/src/github.com/bochs-emu/Bochs/Bochs/bochs/misc/niclist.c:77
  2    Thread 3972.0x39b8 0x00007ff9be390b44 in ntdll!ZwWaitForWorkViaWorkerFactory () from /c/Windows/SYSTEM32/ntdll.dll
(gdb) #
(gdb) c
Continuing.
[New Thread 3972.0xea4]
[New Thread 3972.0x172c]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ff9bdc5dc65 in strtok () from /c/Windows/System32/msvcrt.dll
(gdb) bt
#0  0x00007ff9bdc5dc65 in strtok () from /c/Windows/System32/msvcrt.dll
#1  0x00007ff66f041639 in main (argc=1, argv=0xb224b0) at D:/_BACKUPS/src/github.com/bochs-emu/Bochs/Bochs/bochs/misc/niclist.c:104
(gdb) #
(gdb) info th
  Id   Target Id          Frame
* 1    Thread 3972.0x174c 0x00007ff9bdc5dc65 in strtok () from /c/Windows/System32/msvcrt.dll
  2    Thread 3972.0x39b8 0x00007ff9be390b44 in ntdll!ZwWaitForWorkViaWorkerFactory () from /c/Windows/SYSTEM32/ntdll.dll
  3    Thread 3972.0xea4  0x00007ff9be390b44 in ntdll!ZwWaitForWorkViaWorkerFactory () from /c/Windows/SYSTEM32/ntdll.dll
  4    Thread 3972.0x172c 0x00007ff9be390b44 in ntdll!ZwWaitForWorkViaWorkerFactory () from /c/Windows/SYSTEM32/ntdll.dll
(gdb) #
(gdb) list
72
73      int CDECL main(int argc, char **argv)
74      {
75          int i;
76          HINSTANCE     hPacket;
77          char          AdapterInfo[NIC_BUFFER_SIZE] = { '\0','\0' };
78          ULONG         AdapterLength = NIC_BUFFER_SIZE;
79          LPWSTR        wstrName;
80          LPSTR         strName, strDesc;
81          int           nAdapterCount;
(gdb)
82          PCHAR         dllVersion;
83          PCHAR         testString;
84          int           nDLLMajorVersion, nDLLMinorVersion;
85
86          // Attemp to load the WinpCap packet library
87          hPacket = LoadLibrary("PACKET.DLL");
88          if (hPacket)
89          {
90              // Now look up the address
91              PacketGetAdapterNames = (PGetAdapterNames)GetProcAddress(hPacket, "PacketGetAdapterNames");
(gdb)
92              PacketGetVersion = (PGetVersion)GetProcAddress(hPacket, "PacketGetVersion");
93          } else {
94              printf("Could not load WinPCap driver!\n");
95              printf ("You can download them for free from\n");
96              printf ("http://www.winpcap.org/\n");
97              myexit(1);
98          }
99
100         // Get DLL Version and Tokenize
101         dllVersion = PacketGetVersion();
(gdb)
102         nDLLMajorVersion = -1;
103         nDLLMinorVersion = -1;
104         for (testString = strtok(dllVersion, ",. ");
105                   testString != NULL; testString = strtok(NULL, ",. "))
106         {
107             // If Single Character, Convert
108             if (strlen( testString ) == 1)
109             {
110                 // Check Major First
111                 if (nDLLMajorVersion == -1)
(gdb) info source
Current source file is D:/_BACKUPS/src/github.com/bochs-emu/Bochs/Bochs/bochs/misc/niclist.c
Compilation directory is D:\_BACKUPS\src\github.com\bochs-emu\Bochs\Bochs\bochs\misc
Located in /d/_BACKUPS/src/github.com/bochs-emu/Bochs/Bochs/bochs/misc/niclist.c
Contains 199 lines.
Source language is c.
Producer is GNU C17 13.2.0 -mtune=generic -march=nocona -g.
Compiled with DWARF 5 debugging format.
Does not include preprocessor macro info.
(gdb) br niclist.c:104
Breakpoint 2 at 0x7ff66f041623: file D:/_BACKUPS/src/github.com/bochs-emu/Bochs/Bochs/bochs/misc/niclist.c, line 104.
(gdb) kill
Kill the program being debugged? (y or n) y
[Inferior 1 (process 3972) killed]
(gdb) #
(gdb) r
Starting program: /D/_BACKUPS/src/github.com/bochs-emu/Bochs/Bochs/bochs/misc/niclist.exe
[New Thread 7640.0x2734]

Thread 1 hit Breakpoint 1, main (argc=1, argv=0x1b24b0) at D:/_BACKUPS/src/github.com/bochs-emu/Bochs/Bochs/bochs/misc/niclist.c:77
77          char          AdapterInfo[NIC_BUFFER_SIZE] = { '\0','\0' };
(gdb) c
Continuing.
[New Thread 7640.0x5dc]
[New Thread 7640.0x133c]

Thread 1 hit Breakpoint 2, main (argc=1, argv=0x1b24b0) at D:/_BACKUPS/src/github.com/bochs-emu/Bochs/Bochs/bochs/misc/niclist.c:104
104         for (testString = strtok(dllVersion, ",. ");
(gdb) bt
#0  main (argc=1, argv=0x1b24b0) at D:/_BACKUPS/src/github.com/bochs-emu/Bochs/Bochs/bochs/misc/niclist.c:104
(gdb) list
99
100         // Get DLL Version and Tokenize
101         dllVersion = PacketGetVersion();
102         nDLLMajorVersion = -1;
103         nDLLMinorVersion = -1;
104         for (testString = strtok(dllVersion, ",. ");
105                   testString != NULL; testString = strtok(NULL, ",. "))
106         {
107             // If Single Character, Convert
108             if (strlen( testString ) == 1)
(gdb) next

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ff9bdc5dc65 in strtok () from /c/Windows/System32/msvcrt.dll
(gdb)
```

So the it's `strtok()` that generates access violation.

**Comment by stlintel** [comment]
Can we close this item ?

**Comment by sskras** [comment]
Stanislav, thanks for reviewing my PR. 

> Can we close this item ?

Morally yes.  But could it wait for a new release of binaries? :)

Other users who install the latest release 2.7 still might get confused (in a similar way).

**Comment by stlintel** [comment]
2.8 coming soon :)

**Comment by Vort** [comment]
> But could it wait for a new release of binaries? :)

In case of #167 merging, new binaries will be available with each commit.
